const contactsActionTypes = {
    SET_CONTACTS: "SET_CONTACTS",
    SEARCH_VALUE: "SEARCH_VALUE",
    ADD_NEW_CONTACT: "ADD_NEW_CONTACT",
    DELETE_CONTACT: "DELETE_CONTACT",
    UPDATE_CONTACT: "UPDATE_CONTACT",

    ON_SET_CONTACTS: "ON_SET_CONTACTS",
    ON_ADD_NEW_CONTACT: "ON_ADD_NEW_CONTACT",
    ON_EDIT_CONTACT: "ON_EDIT_CONTACT",
    CONTACTS_IN_FAILURE: "CONTACTS_IN_FAILURE",
    
    
  };
  
  export default contactsActionTypes;